OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = yes
MUSIC_ENABLE = yes
VIA_ENABLE = yes
SWAP_HANDS_ENABLE = no

DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

MOUSEKEY_ENABLE = yes

DYNAMIC_KEYMAP_LAYER_COUNT = 5

#HAPTIC FEEBACK
SPLIT_HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = yes
